---
title: "TP2"
author: "Capucchio Tomás, Milito Manuel y Padoan Renzo"
format: html
editor: visual
---

## Trabajo Práctico Big Data

### Librerías

```{r}
library(usethis)
library(tidyverse)
library(ggplot2)
library(caret)
library(nnet)
library(NeuralNetTools)
```

### Ajustando modelo deep learning

```{r}

bank_test <- read.delim("C:/Git Projects/BigData_TP2/bank_test.txt")
bank_train <- read.delim("C:/Git Projects/BigData_TP2/bank_train.txt")
View(bank_test)
View(bank_train)
```

```{r}
#Separamos en datos para entrenar el modelo y en datos para validarlo
filas <- createDataPartition(bank_train$y,p = 0.80 )[[1]]
train <- slice(bank_train, filas)
validate <- slice(bank_train, -filas)
```

```{r}
set.seed(1)
grilla <- expand.grid(size = c(3, 5, 8), decay = c(0.1, 1.5, 5))
rn <- train(y ~ ., 
            data = dig_train,
            method = "nnet",
            preProc = "range", # Reescalado de variables en [0,1]
            tuneGrid = grilla,
            trControl = trainControl(method = "cv", number = 5), 
            maxit = 200,
            trace = FALSE)
```
